/* ---------------------------------------------------------------------------
 * KATHA · Catalogue seed generator (Sprint 13 — Cloud Catalogue)
 *
 * Emits supabase/seed.sql from the compiled catalogue — lib/books.ts and
 * lib/authors.ts remain the single authoring source; the database receives
 * their content VERBATIM (prose is escaped for SQL quoting only, never
 * altered — the house rule about authored text applies to tooling too).
 *
 * Idempotent: every row upserts by id under seed-reserved id prefixes
 * (the static author ids, "work_seed_", "ch_seed_"), so re-running
 * refreshes seeded content without touching anything a real author writes.
 *
 * Regenerate with:
 *   node --experimental-strip-types --import ./scripts/ts-resolve-hook.mjs \
 *     scripts/generate-catalogue-seed.ts > supabase/seed.sql
 * ------------------------------------------------------------------------- */

import { getAllBooks } from '../lib/books';
import { getAllAuthors } from '../lib/authors';
import { serializeManuscript } from '../lib/studio/work';

function sq(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'null';
  return `'${value.replace(/'/g, "''")}'`;
}

function sqBool(value: boolean | undefined): string {
  return value ? 'true' : 'false';
}

function sqInt(value: number | null | undefined): string {
  return value === null || value === undefined ? 'null' : String(value);
}

const lines: string[] = [
  '-- GENERATED by scripts/generate-catalogue-seed.ts — do not edit by hand.',
  '-- Seeds the compiled demo catalogue into authors/works/chapters.',
  '-- Idempotent: upserts by seed-reserved ids only.',
  '',
];

for (const author of getAllAuthors()) {
  lines.push(
    `insert into public.authors (id, user_id, slug, display_name, bio, location, avatar_url, banner_url) values (` +
      `${sq(author.id)}, null, ${sq(author.slug)}, ${sq(author.displayName)}, ${sq(author.bio)}, ${sq(author.location)}, ${sq(author.avatar)}, ${sq(author.banner)})` +
      ` on conflict (id) do update set slug = excluded.slug, display_name = excluded.display_name, bio = excluded.bio, location = excluded.location, avatar_url = excluded.avatar_url, banner_url = excluded.banner_url;`,
  );
}
lines.push('');

for (const book of getAllBooks()) {
  const workId = `work_seed_${book.slug}`;
  lines.push(
    `insert into public.works (id, author_id, lifecycle, slug, title, category, language, status, synopsis, cover_url, created_at, updated_at, published_at, featured, free_chapters) values (` +
      `${sq(workId)}, ${sq(book.authorId)}, 'published', ${sq(book.slug)}, ${sq(book.title)}, ${sq(book.category)}, ${sq(book.language)}, ${sq(book.status)}, ${sq(book.synopsis)}, ${sq(book.cover)}, ${sq(book.publishedAt)}, ${sq(book.publishedAt)}, ${sq(book.publishedAt)}, ${sqBool(book.featured)}, ${sqInt(book.freeChapters)})` +
      ` on conflict (id) do update set author_id = excluded.author_id, lifecycle = excluded.lifecycle, slug = excluded.slug, title = excluded.title, category = excluded.category, language = excluded.language, status = excluded.status, synopsis = excluded.synopsis, cover_url = excluded.cover_url, updated_at = excluded.updated_at, published_at = excluded.published_at, featured = excluded.featured, free_chapters = excluded.free_chapters;`,
  );
  for (const chapter of book.chapters) {
    const chapterId = `ch_seed_${book.slug}_${chapter.number}`;
    lines.push(
      `insert into public.chapters (id, work_id, position, slug, title, manuscript) values (` +
        `${sq(chapterId)}, ${sq(workId)}, ${chapter.number}, ${sq(chapter.slug)}, ${sq(chapter.title)}, ${sq(serializeManuscript(chapter.content))})` +
        ` on conflict (id) do update set position = excluded.position, slug = excluded.slug, title = excluded.title, manuscript = excluded.manuscript;`,
    );
  }
  lines.push('');
}

process.stdout.write(lines.join('\n'));
